List<Map<String, dynamic>> minhasReceitas = [
  {
    "titulo": "Parmegiana de Berinjela",
    "descricao": "Receita muito boa",
    "estaFavoritada": false,
    "porcoes": 4,
    "tempoPreparo": 60,
    "categorias": ["Vegetariana", "Parmegiana"],
    "ingredientes": [
      "2 berinjelas grandes",
      "Sal a gosto",
      "1/2 xícara de farinha de trigo",
      "2 ovos batidos",
      "1 xícara de farinha de rosca",
      "Óleo para fritar",
      "2 xícaras de molho de tomate",
      "250 g de muçarela fatiada",
      "50 g de parmesão ralado",
      "Pimenta-do-reino a gosto",
    ],
    "modoPreparo": [
      "Corte as berinjelas em fatias de 0,5 cm e salpique sal. Deixe descansar 10 minutos.",
      "Seque as fatias, passe na farinha de trigo, depois nos ovos e, por fim, na farinha de rosca.",
      "Frite em óleo quente até dourar. Escorra em papel-toalha.",
      "Em um refratário, faça camadas de berinjela, molho de tomate e muçarela.",
      "Finalize com parmesão e leve ao forno pré-aquecido a 200°C por 20 minutos para gratinar.",
      "Sirva quente e ajuste sal e pimenta a gosto.",
    ],
  },
  {
    "titulo": "Parmegiana de Frango",
    "descricao": "Receita muito boa mesmo",
    "estaFavoritada": false,
    "porcoes": 4,
    "tempoPreparo": 45,
    "categorias": ["Aves", "Parmegiana"],
    "ingredientes": [
      "600 g de peito de frango em bifes finos",
      "Sal a gosto",
      "Pimenta-do-reino a gosto",
      "2 dentes de alho amassados",
      "1/2 xícara de farinha de trigo",
      "2 ovos batidos",
      "1 xícara de farinha de rosca",
      "Óleo para fritar",
      "2 xícaras de molho de tomate",
      "250 g de muçarela fatiada",
      "50 g de parmesão ralado",
    ],
    "modoPreparo": [
      "Tempere os bifes com sal, pimenta e alho. Descanse por 10 minutos.",
      "Empane passando na farinha de trigo, depois nos ovos e, por fim, na farinha de rosca.",
      "Frite em óleo quente até dourar e cozinhar por dentro. Escorra.",
      "Transfira para um refratário, cubra com molho de tomate e muçarela.",
      "Polvilhe parmesão e leve ao forno a 200°C por 15–20 minutos para gratinar.",
      "Sirva imediatamente com acompanhamentos de sua preferência.",
    ],
  },
  {
    "titulo": "Lasanha",
    "descricao": "Hmmm, lasanha",
    "estaFavoritada": false,
    "porcoes": 6,
    "tempoPreparo": 70,
    "categorias": ["Massas", "Italiana"],
    "ingredientes": [
      "300 g de massa para lasanha (pré-cozida)",
      "500 g de carne moída",
      "1 cebola picada",
      "2 dentes de alho picados",
      "3 xícaras de molho de tomate",
      "300 g de muçarela fatiada",
      "200 g de presunto fatiado",
      "60 g de queijo parmesão ralado",
      "1 colher de sopa de azeite",
      "Sal a gosto",
      "Pimenta-do-reino a gosto",
    ],
    "modoPreparo": [
      "Refogue a cebola e o alho no azeite. Junte a carne e cozinhe até dourar.",
      "Adicione o molho de tomate, ajuste sal e pimenta e cozinhe por 10 minutos.",
      "Em um refratário, monte camadas de molho, massa, presunto e muçarela. Repita as camadas.",
      "Finalize com molho e parmesão ralado por cima.",
      "Leve ao forno pré-aquecido a 200°C por 30–40 minutos, até borbulhar e gratinar.",
      "Descanse por 10 minutos antes de cortar e servir.",
    ],
  },
];
