// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3xv5IHcUdmK-_pyDfAEdpN93zqJ1zIg',
    appId: '1:454268535147:web:0e131ee78fdc88f8a98c2e',
    messagingSenderId: '454268535147',
    projectId: 'receitas-app-2468f',
    authDomain: 'receitas-app-2468f.firebaseapp.com',
    storageBucket: 'receitas-app-2468f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6iCem2eiPZrQc0fdQqeYczLY1Yk_z8Y',
    appId: '1:454268535147:android:e2ce3f452ec9b329a98c2e',
    messagingSenderId: '454268535147',
    projectId: 'receitas-app-2468f',
    storageBucket: 'receitas-app-2468f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGxssLDxqW89WEzLTskNsnUJ7HYFhJXDE',
    appId: '1:454268535147:ios:855269c2af9cf963a98c2e',
    messagingSenderId: '454268535147',
    projectId: 'receitas-app-2468f',
    storageBucket: 'receitas-app-2468f.firebasestorage.app',
    iosBundleId: 'com.example.aulaStlStf',
  );
}
